### ISSUE TITLE
Thêm nút logout, chuyển từ route qua trang default -> xoá thông tin => khi nhất btn logout mới xoá thông tin

### ISSUE THREAD

**Issue by huyvu8051** [huyvu8051/huhoot-frontend#12]
![image](https://user-images.githubusercontent.com/70710967/168323451-fda8b6d8-23d2-4f5c-8d13-fcaf3a0cb4ed.png)

thêm nút logout ở dưới đáy navigation bar

**Comment by PhaciusPhat** [comment]
host xong
