### ISSUE TITLE
Chỉnh giao diện trang đổi mật khẩu

### ISSUE THREAD

**Issue by huyvu8051** [huyvu8051/huhoot-frontend#16]
![image](https://user-images.githubusercontent.com/70710967/168324743-1d591602-fcd2-4714-8806-1e9e8e4f021c.png)

**Comment by huyvu8051** [comment]
![image](https://user-images.githubusercontent.com/70710967/168328606-219d8395-fa97-410f-9d41-ee16df48ccc0.png)

trang sinh viên và admin

**Comment by PhaciusPhat** [comment]
host xong
